### PR TITLE
Desugar

### PR DESCRIPTION
**Pull request by Unit112358**
I implemented desugar.nim and add some elements of il (Realloc, Ptrset and Ptrget), but i haven't implemented error handling yet.
So, the code below would be error.
```nim
type a = typeof(1, 2)     # 2 arguments are passed but expected 1
```
How(or Where) should I implement it?

### CODE REVIEW

**Comment by Unit112358** [comment]
p.s.
Thanks for your advice "it just replace inst in inst.nim to desugar" you told yesterday. This task was completed 10 times faster than I expected.

**Comment by chocobo333** [comment]
I have a suggestion to define `enum` like follows
```suggestion
type PremitiveKeyWord = enum
  PKTypeof = "typeof"
  PKPtrSet = "ptrset"
  ...
```
in il.nim

**Comment by Unit112358** [comment]
Sorry. This code contains bugs.

**Comment by Unit112358** [comment]
Fixed

**Pull request merged**
